name: Testing

on:
  - pull_request:
    branches:
      - main
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install tox tox-gh-actions
      - name: Test with tox
        run: tox
      - name: Getting coverage report
        if: github.event_name == 'push' && github.repository == 'Vader19695/django-chunky-upload' && matrix.python-version == '3.10' && github.ref_name == 'main'
        run: tox -e coverage
      - name: Publish coverage to Coveralls
        # If pushed / is a pull request against main repo AND
        # we're running on Linux (this action only supports Linux)
        if: github.event_name == 'push' && github.repository == 'Vader19695/django-chunky-upload' && matrix.python-version == '3.10' && github.ref_name == 'main'

        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          github-token: ${{ secrets.COVERALLS_TOKEN }}
          parallel: true
          flag-name: py${{ matrix.python-version }}-${{ matrix.os }}
          debug: true

  coveralls-finish:
    needs: build
    # If pushed / is a pull request against main repo
    if: github.event_name == 'push' && github.repository == 'Vader19695/django-chunky-upload' && github.ref_name == 'main'

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Coveralls finished
        uses: AndreMiras/coveralls-python-action@v20201129
        with:
          parallel-finished: true
          debug: true
